import type { Metadata } from "next";

const siteUrl = "https://www.footballparent.co.uk";

// Shared brand preview images, generated by scripts/generate-og-images.mjs
// from the horizontal lockup. One file per aspect ratio a preview surface
// actually uses, each with the logo centred in the crop-safe zone:
//   1200x630  og:image / twitter:image (Facebook, WhatsApp, LinkedIn, Slack,
//             iMessage, Instagram DMs, X)
//   16:9, 4:3, 1:1  Google Article structured data (Discover, rich results,
//             AI Overview thumbnails), listed by lib/ArticleLayout.tsx
// Re-run the script rather than editing the PNGs by hand.
export const BRAND_IMAGE = {
  og: { url: `${siteUrl}/og/football-parent-1200x630.png`, width: 1200, height: 630 },
  wide: `${siteUrl}/og/football-parent-1200x675.png`,
  standard: `${siteUrl}/og/football-parent-1200x900.png`,
  square: `${siteUrl}/og/football-parent-1200x1200.png`,
} as const;

type SEOProps = {
  title: string;
  description: string;
  path: string;
  type?: "article" | "website";
  image?: string;
};

export function generateSEO({
  title,
  description,
  path,
  type = "article",
  image,
}: SEOProps): Metadata {
  const url = `${siteUrl}${path}`;
  const ogImage = image
    ? { url: `${siteUrl}${image}`, alt: title }
    : { ...BRAND_IMAGE.og, type: "image/png", alt: "Football Parent" };

  return {
    title,
    description,
    alternates: {
      canonical: url,
    },
    openGraph: {
      title,
      description,
      url,
      siteName: "Football Parent",
      locale: "en_GB",
      type,
      images: [ogImage],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [ogImage],
    },
  };
}