import type { Metadata } from "next";

const siteUrl = "https://www.footballparent.co.uk";

// Shared brand preview images, generated by scripts/generate-og-images.mjs
// from the horizontal lockups: one set for the site, one for the Coach App
// pages. One file per aspect ratio a preview surface actually uses, each
// with the logo centred in the crop-safe zone:
//   1200x630  og:image / twitter:image (Facebook, WhatsApp, LinkedIn, Slack,
//             iMessage, Instagram DMs, X)
//   16:9, 4:3, 1:1  Google structured data (Discover, rich results,
//             AI Overview thumbnails): BlogPosting image in
//             lib/ArticleLayout.tsx, SoftwareApplication image on the
//             Coach App landing page
// Re-run the script rather than editing the PNGs by hand.
export type Brand = "parent" | "coach";

function brandImages(prefix: string) {
  return {
    og: { url: `${siteUrl}/og/${prefix}-1200x630.png`, width: 1200, height: 630 },
    wide: `${siteUrl}/og/${prefix}-1200x675.png`,
    standard: `${siteUrl}/og/${prefix}-1200x900.png`,
    square: `${siteUrl}/og/${prefix}-1200x1200.png`,
  } as const;
}

export const BRAND_IMAGES: Record<Brand, ReturnType<typeof brandImages>> = {
  parent: brandImages("football-parent"),
  coach: brandImages("coach-app"),
};

// The og:image entry for a brand, in the shape both openGraph.images and
// twitter.images accept.
export function brandOgImage(brand: Brand = "parent") {
  const alt = brand === "coach" ? "Football Parent Coach App" : "Football Parent";
  return { ...BRAND_IMAGES[brand].og, type: "image/png", alt };
}

type SEOProps = {
  title: string;
  description: string;
  path: string;
  type?: "article" | "website";
  image?: string;
  // Which lockup the preview carries. Coach App pages pass "coach".
  brand?: Brand;
};

export function generateSEO({
  title,
  description,
  path,
  type = "article",
  image,
  brand = "parent",
}: SEOProps): Metadata {
  const url = `${siteUrl}${path}`;
  const ogImage = image ? { url: `${siteUrl}${image}`, alt: title } : brandOgImage(brand);

  return {
    title,
    description,
    alternates: {
      canonical: url,
    },
    openGraph: {
      title,
      description,
      url,
      siteName: "Football Parent",
      locale: "en_GB",
      type,
      images: [ogImage],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [ogImage],
    },
  };
}