// Parses drafted social copy out of content_queue.topic. For source='gsc'
// items, topic is generated by buildTopic() in ideation-flow.ts:
//
//   <hook>
//
//   Points:
//   1. <point>
//   2. <point>
//
//   Source: <pathname>, targeting "<query>" (<impressions> impressions, position <n>)
//
// Other sources (manual/chat) currently store a plain-text brief, not drafted
// copy - topic.structured is false for those, and QC treats the whole string
// as an unstructured hook with no points.

export interface ParsedDraft {
  hook: string;
  points: string[];
  sourceLine: string | null;
  structured: boolean;
  raw: string;
}

const POINTS_HEADER = /\n\nPoints:\n/;
const SOURCE_HEADER = /\n\nSource:\s*/;
const NUMBERED_POINT = /^\d+\.\s+(.+)$/;

export function parseDraftedTopic(topic: string): ParsedDraft {
  const raw = topic.trim();

  const pointsMatch = raw.match(POINTS_HEADER);
  if (!pointsMatch || pointsMatch.index === undefined) {
    return { hook: raw, points: [], sourceLine: null, structured: false, raw };
  }

  const hook = raw.slice(0, pointsMatch.index).trim();
  const afterPoints = raw.slice(pointsMatch.index + pointsMatch[0].length);

  const sourceMatch = afterPoints.match(SOURCE_HEADER);
  const pointsBlock = sourceMatch && sourceMatch.index !== undefined ? afterPoints.slice(0, sourceMatch.index) : afterPoints;
  const sourceLine = sourceMatch && sourceMatch.index !== undefined ? afterPoints.slice(sourceMatch.index + sourceMatch[0].length).trim() : null;

  const points = pointsBlock
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      const m = line.match(NUMBERED_POINT);
      return m ? m[1].trim() : line;
    });

  return { hook, points, sourceLine, structured: true, raw };
}

// The visible copy a reader would actually see - excludes the Source
// provenance line, which is internal metadata, not customer-facing text.
export function visibleCopy(parsed: ParsedDraft): string {
  return [parsed.hook, ...parsed.points].filter(Boolean).join("\n");
}
